require('modules/lualine')
require('modules/nvim-tree')
require('modules/treesitter')
require('modules/toggleterm')
require('modules/telescope')
require('modules/nvim-cmp')
require('modules/brackets')
require('modules/vgit')
