format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_status\
$vcsh\
$character"""

right_format = "$cmd_duration"

palette = "catppuccin_mocha"


[line_break]
disabled = true

[character]
success_symbol = " [>](bold mauve)"
error_symbol = "[>](bold red) "

[cmd_duration]
min_time = 1
format = "[$duration]($style)"
style = "green bold"

[directory]
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "blue"
truncate_to_repo = true
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
format = "on [$symbol$branch ]($style)"
symbol = " "
style = "bold purple"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "bold green"

[git_status]
format ='([\[$all_status$ahead_behind\]]($style))'
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"
style =	"bold red"
disabled = false

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[time]
disabled = false
format = '[$time](fg:245) '

[[battery.display]]
threshold = 15
style = "red"


[[battery.display]]
threshold = 100
style = "green"


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
